baseURL                   = "https://juliegund.netlify.com"
builddrafts                = false
languageCode               = "en-US"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Julie Gunderson"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Speaking"
    weight                 = -110
    identifier             = "speaking"
    url                    = "https://noti.st/juliegund" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "img/profile.png"             # path to image in static dir e.g img/avatar.png 
  author                   = "Julie Gunderson"
  description              = ["DevOps Advocate", "Sparkly DevOps Princess", "Builder of Community"]           # appears in the site header when set to a non-empty string
#   welcome_head             = "Hello, World!"
#   welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides-julie"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides-julie"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "juliegund@gmail.com"
  github                   = "//github.com/juliegund"
  linkedin                 = "//linkedin.com/in/juliegunderson"
#   facebook                 = "//facebook.com/you"
#   googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/Julie_Gund" 
#   px500                    = "//px500"
#   instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    